### ISSUE TITLE
Cooking Campfire opens Hiking Bag inventory (cannot add coal to cook). 1.8

### ISSUE THREAD

**Issue by Jerimon1998** [Rikmuld/MC-Camping#61] opened 2015-09-12 20:07 UTC
Every time I try to put coal in it, it just gives me an inventory named Hiking Bag, or does nothing.
The inventory appears when I right click with an item (any item) in hand, and the inventory changes with each item. I cannot put the "opened" item in, but everything else can go in. Nothing happens when I click with an empty hand.

Finally, the campfire will open the pan kit I tried with it. It did the same with the backpack. The items that were in them were there and removable.

BTW, I have InventoryTweaks, which modifies the GUI of inventories slightly (organization buttons), and NEI, which would allow me to grab an indev item if it is the functional version. Of course, I crafted the campfire base to ensure that I had the correct one.

Update: When I went singleplayer on sunday during the mojang server outage, the campfire and tent worked just fine, so these are only problems on servers for some reason.

**Comment by erian-7** [comment] 2015-10-15 01:05
Confirmed here as well. It only happens Server-side, and I noted the following in the Game Output log:

[18:38:30] [Client thread/ERROR] [RadixCore]: catching
java.lang.NullPointerException
	at radixcore.packets.PacketDataSync.processOnGameThread(PacketDataSync.java:62) [PacketDataSync.class:?]
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:164) [AbstractPacketHandler.class:?]
	at radixcore.core.RadixEvents.clientTickEventHandler(RadixEvents.java:88) [RadixEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_RadixEvents_clientTickEventHandler_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:366) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1618) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1029) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:38:30] [Client thread/ERROR] [RadixCore]: Unexpected exception/(Unexpected error while processing received sync data.). null
[18:38:30] [Client thread/ERROR] [RadixCore]: catching
java.lang.NullPointerException
	at radixcore.packets.PacketDataSync.processOnGameThread(PacketDataSync.java:62) [PacketDataSync.class:?]
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:164) [AbstractPacketHandler.class:?]
	at radixcore.core.RadixEvents.clientTickEventHandler(RadixEvents.java:88) [RadixEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_RadixEvents_clientTickEventHandler_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:366) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1618) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1029) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:38:30] [Client thread/ERROR] [RadixCore]: Unexpected exception/(Unexpected error while processing received sync data.). null

**Comment by louiscroudace** [comment] 2015-10-18 07:57
delete radix core for whatever reason you are using it for but it seems that it is not compatible with radix core.

**Comment by Jerimon1998** [comment] 2015-10-18 17:19
I am not using radix core, and I am still having this problem. Radix core may have its own issues, however.

**Comment by erian-7** [comment] 2015-10-18 17:56
RadixCore is for the mod Minecraft Comes Alive. It seems odd that it fires off an error message when trying to open the cooking campfire. I'll experiment without it in play, but from Jerimon1998's statement it looks like it's not a factor in the error occurring.

**Comment by teragen** [comment] 2015-11-08 09:13
Confirmed here as well, and also not using RadixCore.  Only happens server side.  If I run the exact same selection of mods in a single player map, works perfectly.  Have noticed that when running from server, it tends to treat whatever you are attempting to put into the campfire as a form of container, treating it as a Hiking Bag.  I've gone so far as to attempt to place coal in the fire, then put a stone sword in the "bag", switched the coal for something else, then switched back and retrieved the sword.

Haven't coded with MC, but looks to be grabbing the wrong object reference when looking at contents.

**Comment by Rikmuld** [comment] 2016-01-23 16:46
Resolved in https://github.com/Rikmuld/MC-Camping/commit/8bca5a1d54ae90f7faa3933b06c526f9a22c52c7

**Closed by Rikmuld** 2016-01-23 16:46 UTC
